name: cxr
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - ipykernel=6.2.0
  - matplotlib=3.4.2
  - numpy=1.20.3
  - pandas=1.3.2
  - pillow=8.3.1
  - python=3.9.6
  - pytorch=1.9.0
  - scikit-learn=0.24.2
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - tqdm=4.62.2
  - pip:
    - opacus==0.14.0
